수정

diff --git a/.github/workflows/aws-deploy-server.yml b/.github/workflows/aws-deploy-server.yml
--- a/.github/workflows/aws-deploy-server.yml
+++ b/.github/workflows/aws-deploy-server.yml
@@ -42,17 +42,16 @@ jobs:
       - name: Build with Gradle
         run: |
           ./gradlew bootJar --refresh-dependencies --no-daemon --stacktrace --info
-      
 
-      - name: Docker Build and Push payment server image
+      - name: Docker Build and Push main server image
         env:
           DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
           DOCKER_HUB_REPOSITORY: ${{ secrets.DOCKER_HUB_REPOSITORY }}
         run: |
           echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
-          docker build --no-cache -t "$DOCKER_HUB_REPOSITORY":payment -f payment-server/Dockerfile ./payment-server
-          docker push "$DOCKER_HUB_REPOSITORY":payment
+          docker build --no-cache -t "$DOCKER_HUB_REPOSITORY":pillyohae -f main-server/Dockerfile ./main-server
+          docker push "$DOCKER_HUB_REPOSITORY":pillyohae
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
@@ -83,6 +82,62 @@ jobs:
           OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
           TZ=Asia/Seoul
           EOF
+
+      - name: SSH into server and prepare environment
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.AWS_MAIN_SERVER_SSH_HOST }}
+          username: ${{ secrets.AWS_SSH_USERNAME }}
+          key: ${{ secrets.AWS_SSH_KEY }}
+          port: 22
+          script: |
+            echo "=== 기존 파일 정리 ==="
+            sudo rm -rf ~/app/*
+            mkdir -p ~/app
+
+      - name: Copy env files to main server
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.AWS_MAIN_SERVER_SSH_HOST }}
+          username: ${{ secrets.AWS_SSH_USERNAME }}
+          key: ${{ secrets.AWS_SSH_KEY }}
+          port: 22
+          source: "./.env"
+          target: "~/app/"
+
+      - name: Copy docker-compose file to main server
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.AWS_MAIN_SERVER_SSH_HOST }}
+          username: ${{ secrets.AWS_SSH_USERNAME }}
+          key: ${{ secrets.AWS_SSH_KEY }}
+          port: 22
+          source: "./main-server/docker-compose.yml"
+          target: "~/app/"
+
+
+      - name: SSH into server and deploy main server
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.AWS_MAIN_SERVER_SSH_HOST }}
+          username: ${{ secrets.AWS_SSH_USERNAME }}
+          key: ${{ secrets.AWS_SSH_KEY }}
+          port: 22
+          script: |
+            echo "=== Docker 로그인 ==="
+            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+            sleep 5
+            echo "=== DOCKER COMPSE 파일 이동 및 디렉토리 삭제 ==="
+            mv ~/app/main-server/docker-compose.yml ~/app/docker-compose.yml
+            echo "=== 파일 확인 ==="
+            ls -la ~/app/
+            cat ~/app/docker-compose.yml || echo "docker-compose.yml not found"
+            cat ~/app/.env
+            echo "=== Docker Compose 실행 ==="
+            cd ~/app
+            sudo docker compose down || true
+            sudo docker compose pull
+            sudo docker compose up -d --remove-orphans
 
       - name: SSH into server and prepare environment
         uses: appleboy/ssh-action@master
